### ISSUE TITLE
footer 解析有点异常

### ISSUE THREAD

**Issue by findmyway** [laike9m/zhihu-card#1]
这个card显示的footer部分是怎么解析的呀？
我刚刚试用了下，footer提取的字符好像少了一部分。

![image](https://cloud.githubusercontent.com/assets/5612003/18879718/f3527002-8507-11e6-8828-1ef116fca666.png)

上图中http://tianjun后面应该还有.ml

**Comment by laike9m** [comment]
主要是考虑到有些人的自我介绍太长了，导致下面文字很多不美观。所以只截取了第一句话。但是第一句话怎么确定呢？一个规则是取到 `.`，所以就把 `.ml` 给去掉了。

我马上改一下，不处理 `.` 应该就可以了，反正也没几个人用。

**Comment by laike9m** [comment]
你再试一下呢？对了，因为用了 localstorage，所以你得把页面的 localstorage 也清一下，会弄吧？

**Comment by findmyway** [comment]
呃，这下直接全没了。。。

![image](https://cloud.githubusercontent.com/assets/5612003/18881794/4f2b7e8a-850f-11e6-9d96-5cd601d4f707.png)

**Comment by laike9m** [comment]
不好意思，能把你的 hash 邮件给我吗？这样我好调试一下……

**Comment by findmyway** [comment]
@laike9m 已发，
我感觉，应该可以根据设定的宽度只显示一行或者两行description，多余的截断就好了

**Comment by laike9m** [comment]
这下终于 ok 了，直接加了个判断，描述在 25 个 byte 以下的直接全返回。

你那个思路是不行的，因为如果只限定显示一行或者两行，会把一整句话给截断，不可能不考虑标点符号。

我把服务端也开源出来算了，方便修改。

**Comment by laike9m** [comment]
https://github.com/laike9m/zhihu-card-server

Fixed: https://github.com/laike9m/zhihu-card-server/commit/ab44a7c412beb4bb5b5d5ed9c3067eb2ab970ae8

**Comment by findmyway** [comment]
> 你那个思路是不行的，因为如果只限定显示一行或者两行，会把一整句话给截断，不可能不考虑标点符号。

有道理！
