### ISSUE TITLE
某些环境下无法正常显示

### ISSUE THREAD

**Issue by laike9m** [laike9m/zhihu-card#3]
![image](https://user-images.githubusercontent.com/2592205/26981966-688193ba-4d69-11e7-8be5-60ed3f999125.png)

经过观察，多了一层 `<pre>`
![image](https://user-images.githubusercontent.com/2592205/26982035-975de404-4d69-11e7-8e68-46a0fd10de4c.png)

原因暂时未知

**Comment by laike9m** [comment]
这个问题无法稳定重现，似乎和
https://groups.google.com/forum/#!topic/google-web-toolkit/TsDJj-oi68U
以及
https://github.com/twilson63/ngUpload/issues/43
有关

**Comment by laike9m** [comment]
根据 jsdelivr 的说法
https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/
应该会根据文件类型决定 response 的 content-type，实际也确实观察到其值为 `text/html`

**Comment by laike9m** [comment]
经过观察，对于请求
```
https://cdn.jsdelivr.net/zhihu-card/0.2.3/theme/github.html?userhash=laike9m&identity=zhcard-laike9m-1&button=no&description=no&key1=answer&key2=agree&key3=follower
```
有时 jsdelivr 的 response content-type 是 `text/plain`，此时会出现显示不正常的状况．

**Comment by laike9m** [comment]
发现，当 github.html 的 response 中，Server 是 `cloudflare-nginx` 时，content-type 是 text/plain。这说明似乎是 cloudflare 的问题。因为 jsdelivr 会使用 MaxCDN, cloudflare 和自己的 server，故只有在从 cloudflare serve 资源的时候才能重现问题。

**Comment by laike9m** [comment]
Fixed as I've migrated to raw git.

**Comment by findmyway** [comment]
我把目前这版的js文件上传到我的qiniu上了（暂时没有https），似乎好使了。

灰常感谢！

**Comment by laike9m** [comment]
我七牛没实名，都不能传 js 😢
