### ISSUE TITLE
GET https://cr-inn.com/v1/user/<zhihu-username> net::ERR_NAME_RESOLUTION_FAILED

### ISSUE THREAD

**Issue by polossk** [laike9m/zhihu-card#4]
首先感谢dalao提供的zhihu-card服务! 在下使用很久了点个赞!
不过最近我维护自己的博客的时候发下zhihu-card服务可能挂了, 具体而言表现在我这边的浏览器会得到一个错误, 具体如图所示
GET https://cr-inn.com/v1/user/<zhihu-username> net::ERR_NAME_RESOLUTION_FAILED
![image](https://user-images.githubusercontent.com/7643570/36710786-1582d5ae-1bbb-11e8-8e7f-5202f75cd126.png)
另外, 我本机不能ping到该域名, 同时dns也查找不到任何记录, 我怀疑可能是后端的服务器跪了. 还麻烦dalao择时更新一发.

**Comment by laike9m** [comment]
事情是这样的。那个域名是买的二手的已备案域名，因为我自己不想去搞备案。其实域名并没有真正转让给我，我只是在转卖域名的这家网站上设置了一个DNS绑定到服务器。后来这家网站倒了……

尝试联系域名的原始拥有者，没有收到回复，于是就一直这样放着了……

现在有两个方案，一个是直接放在美国的VPS上，这样不用备案，但是考虑到用户大多在国内所以会有一些延迟。另一个就是再买个已备案域名，然后绑到之前那台阿里云的服务器。不论哪种，原来的 cr-inn 应该是都没法用了。

**Comment by laike9m** [comment]
搞定了。按当前 README 修改一下地址即可。
