### ISSUE TITLE
使用知乎风格的界面

### ISSUE THREAD

**Issue by frostming** [laike9m/zhihu-card#6]
![image](https://user-images.githubusercontent.com/16336606/66638880-60f54d00-ec48-11e9-8cb9-d25f77121ced.png)

Emmm, 等我看有没有空搞一搞，咱设计虽不行，扒还是能扒的

**Comment by laike9m** [comment]
现在的主题之一是以前知乎的界面😅
不过确实没有新版的。是应该加一个
